### PR TITLE
set the host's time to all containers

### PR DESCRIPTION
**Pull request by Adito5393**
This PR fixes the wrong timestamps when executing `docker logs` commands and future time issues that might arise.

### CODE REVIEW

**Comment by brasseld** [comment]
Hum, I'm thinking about this one.... because of the volume, not sure it works well for non-unix environment....

WDYT?

**Comment by Adito5393** [comment]
Looks like the most elegant way would be to install `tzdata` package via the Dockerfile and set the `TZ` environment variable (e.g. TZ=Europe/Paris) within the docker-compose as mentioned [here](https://unix.stackexchange.com/questions/550734/how-to-synchronize-timezone-in-docker-containers).

**Comment by brasseld** [comment]
Yeah, it looks to be a better idea!

**Comment by gaetanmaisse** [comment]
Closing based on feedback given here: https://github.com/gravitee-io/gravitee-docker/pull/47#issuecomment-652947212

**Pull request closed without merging**
